// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.19.3_@parcel+watcher@2.5.1_@types+node@22.18.11_@vue+compiler-sfc@3.5.22_db0@0.3_f47428926494e4791e7e46858a78e443/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../src/server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}