FROM node:22-alpine

LABEL org.opencontainers.image.authors="Elias Shekh"

WORKDIR /app

RUN npm install -g pnpm

ENV CI=true

COPY package.json pnpm-workspace.yaml ./

RUN pnpm install --ignore-scripts

COPY . .

RUN pnpm postinstall

EXPOSE 3000

CMD ["sh", "-c", "pnpm preview"]
