FROM node:22-slim

LABEL org.opencontainers.image.authors="Elias Shekh"

WORKDIR /app

COPY package.json .

RUN npm i -g pnpm

RUN pnpm i

COPY . .

RUN pnpm run postinstall

RUN pnpm build

CMD ["sh", "-c", "pnpm preview"]

EXPOSE 3000
