// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/18/2025, 2:43:46 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/ThisIsTheWizard/Documents/Projects/Boilerplates/BoilerPlates.NuxtJS_Admin/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ThisIsTheWizard/Documents/Projects/Boilerplates/BoilerPlates.NuxtJS_Admin/src/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ThisIsTheWizard/Documents/Projects/Boilerplates/BoilerPlates.NuxtJS_Admin/src/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ThisIsTheWizard/Documents/Projects/Boilerplates/BoilerPlates.NuxtJS_Admin/src/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ThisIsTheWizard/Documents/Projects/Boilerplates/BoilerPlates.NuxtJS_Admin/src/plugins/**/*.{js,ts,mjs}","/Users/ThisIsTheWizard/Documents/Projects/Boilerplates/BoilerPlates.NuxtJS_Admin/src/composables/**/*.{js,ts,mjs}","/Users/ThisIsTheWizard/Documents/Projects/Boilerplates/BoilerPlates.NuxtJS_Admin/src/utils/**/*.{js,ts,mjs}","/Users/ThisIsTheWizard/Documents/Projects/Boilerplates/BoilerPlates.NuxtJS_Admin/src/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/ThisIsTheWizard/Documents/Projects/Boilerplates/BoilerPlates.NuxtJS_Admin/src/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/ThisIsTheWizard/Documents/Projects/Boilerplates/BoilerPlates.NuxtJS_Admin/src/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/ThisIsTheWizard/Documents/Projects/Boilerplates/BoilerPlates.NuxtJS_Admin/src/app.config.{js,ts,mjs}","/Users/ThisIsTheWizard/Documents/Projects/Boilerplates/BoilerPlates.NuxtJS_Admin/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;